spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.40.27:3306/base?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false
        username: ngsoc
        password: MxJf^Pg$
  redis:
    host: 172.16.40.173
    port: 6379
    username:
    password:
    client-type: lettuce
    connect-timeout: 10000  # 连接超时时间
    database: 0
    lettuce:
      pool:
        max-idle: 50       # 连接池最大空闲连接
        min-idle: 0        # 连接池最小空闲连接
        max-active: 1024   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 500      # 连接最大等待阻塞时间（使用负值表示没有限制）
  #    cluster:  # 集群环境打开
  #      nodes: 192.168.60.113:6379
  #      max-redirects: 3 # 默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections

  elasticsearch:
    username:
    password:
    uris:
      - http://172.16.40.173:9200
  servlet:
    multipart:
      enabled: true #开启文件上传
      #      file-size-threshold: 0
      max-file-size: 300MB #单个数据的大小
      max-request-size: 300MB #总数据的大小
logging:
  config: classpath:config/spring-log4j2.xml
  level:
    root: info

mybatis:
  mapper-locations: classpath:mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
upload:
  upgrade:
    path: /home/unisguard/upgrade/
    api: https://192.168.60.115:16500/unisguard/api/cli/mainUpgrade
  logo:
    # 配置管理/系统配置管理/系统信息配置/LOGO上传地址  例如：D:\unisguard\uploadlogopath\
    path: /home/unisguard/uploadlogopath/